import contentJson from "./data/content.json";

/**
 * Handbook content selected for each assessment page, generated by
 * scripts/assessment-content/build.mjs from the Career Garage handbooks.
 */

export type ContentBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "ul" | "ol"; items: string[] }
  | { type: "table"; rows: string[][] }
  | { type: "callout"; label: string; text: string }
  | { type: "img"; src: string; w: number; h: number; alt: string }
  | { type: "caption"; text: string };

export type ContentSection = {
  id: string;
  title: string;
  lead?: string;
  blocks: ContentBlock[];
};

export type PageContent = {
  sections: ContentSection[];
  faq: {
    items: { q: string; a: ContentBlock[] }[];
    note?: { label: string; text: string };
  };
};

type ContentFile = {
  learnerInstructions: string[];
  listNotes: Record<string, { response: string; note: string }>;
  pages: Record<string, PageContent>;
};

const content = contentJson as unknown as ContentFile;

export function getPageContent(slug: string): PageContent | undefined {
  return content.pages[slug];
}

/** "How to use this list" → Learner Instructions, first four points. */
export const learnerInstructions = content.learnerInstructions;

/** Per-assessment response line and note from the 772-question list. */
export function listNote(id: string) {
  return content.listNotes[id];
}
